### ISSUE TITLE
Crash when right clicking funace gui

### ISSUE THREAD

**Issue by lilmoefow** [Chocohead/Binnie-Patcher#13]
I opened up a vanilla furnace's gui, i went to right click a piece of coal into the fuel slot but accidentally right clicked the gui and crashed to desktop. This happens when i am playing on a SMP server. The crash does not happen in single player.   

Here is a crash log.
http://pastebin.com/Z3SdF6sy 

Not sure why.. but i can not repeat this crash again.. had it happen twice earlier on today.. and once when i got home from work... now when trying to reproduce it in other blocks gui's, i cant even get it to crash again in the vanilla furnace. So im not sure what is going on.

**Comment by Chocohead** [comment]
Curious, I'll try see if I can replicate it

**Comment by Chocohead** [comment]
Next version should fix this or stop it happening. One of those two.

**Comment by lilmoefow** [comment]
any idea when this "next version" will be available?
