### ISSUE TITLE
Apparently unrelated crash only happens when Binnie-Patcher and Binnie's Mods installed

### ISSUE THREAD

**Issue by Sinhika** [Chocohead/Binnie-Patcher#14]
Re-posting this from FtB-forum thread, as that's not the best place for an issue.

 I get this crash (see [Paste.ee link here](http://paste.ee/p/Hb43V) ) with Binnie's Mods pre14 and your patcher 1.6 installed. I don't get it without those two mods installed. Why it shows up as Thermal Expansion throwing a hissy-fit about Metallurgy, I don't know, but it does. TE & Met4 get along fine WITHOUT Binnie's stuff installed. Running the latest updates for most of the installed mods, including Forestry.

**Comment by asiekierka** [comment]
Look around line 1000. I think Met4 might be at fault here, but why Binnie's would trigger that is beyond me - perhaps it changes the mod loading order?

Either way, this is an absolutely amazing crash report.

**Comment by Sinhika** [comment]
I suspect Metallurgy 4 is at fault for several things, including poor ore-dictionary registration practices, but the Metallurgy team fixes things like once every 2 years whether it needs it or not, so I'm not holding my breath waiting for a fix. I was hoping it was something in the ASM code at your end that was Doing Stuff that you could fix. (I probably should bug-report those bad ore-dict registrations to them). Hmm, I'll have to try renaming the Binnie stuff to zzBinnie and see what happens, when I have an afternoon free.

**Comment by Sinhika** [comment]
Okay, renaming Binnies and Binnie-Patcher to zzBinnie, zzBinniePatcher made the crash go away.  I hope Metallurgy pushes their fixes out soon, because I still suspect it has something to do with them screwing up the oreDictionary.

**Comment by Chocohead** [comment]
It's probably that combined with a load order problem if putting zz in front makes it go away.
