### ISSUE TITLE
[Genetics] Crash when selecting Sapling in Registry

### ISSUE THREAD

**Issue by thephoenixlodge** [Chocohead/Binnie-Patcher#16]
As per title, crashed when selecting a sapling in the Trees section of the Registry - specifically the Myrtle Ebony.
Crash Report:
http://pastebin.com/W6NyabSJ

**Comment by Chocohead** [comment]
Oops, not sure how I didn't notice this considering how long ago that function was moved...

Fixed next version

**Comment by thephoenixlodge** [comment]
Does the fix include the analyst too? Just got a virtually identical crash report trying to analyze a sapling in that.

**Comment by Chocohead** [comment]
It should do...

If it doesn't a crash report would be useful.
