### ISSUE TITLE
Crash when pressing CTRL+SHIFT with Binnie/Patcher/ChromatiCraft

### ISSUE THREAD

**Issue by Haggle1996** [Chocohead/Binnie-Patcher#17]
Crashlog
https://gist.github.com/Haggle1996/e349c8d4c714f5eea0436368a10ad15d

Pressing CTRL when hovering over an item reveals it's ChromatiCraft element information, which is where this error seems to occur. My players encounter this frequently because they SHIFT+CLICK (a feature of InventoryTweaks) items between inventories.

This error did not occur prior to adding Binnie/Binnie Patcher to my pack, and I've narrowed it down to just the addition of these two mods causing the problem. That doesn't mean the problem is in Binnie's or the patcher code, but something in the interaction.

**Comment by Chocohead** [comment]
Silly Reika not liking OreDict.WILDCARD most likely, might see if it's fixable but disabling V12's environment meddling is the best temporary fix I'd expect.

**Comment by Haggle1996** [comment]
Actually, enabling his environment meddling fixes the crash...but then many recipes stop working. :P

**Comment by Chocohead** [comment]
0_o then I'm not sure why this crashes, guess I'll just have to put a defensive if check in

**Comment by Chocohead** [comment]
The latest version might fix this. But knowing Rekia something else will probably break instead

**Comment by Haggle1996** [comment]
Thank you very much! Looks like it's fixed in the last update.

**Comment by Chocohead** [comment]
Excellent
