### ISSUE TITLE
crash client when opening the interface Botanist Database

### ISSUE THREAD

**Issue by lex1975** [Chocohead/Binnie-Patcher#19]
Regular crash client when opening the interface arborist Database. BinniePatcher v.1.7
Version 1.6 work fine.

My modlist:
[1.7.10] The Lord of the Rings Mod B28.2.jar
[1.7.10]Treecapitator-universal-2.0.4.jar
ABO-MC1.7.10-BC7.1release4.0.8-ru.jar
advancedgenetics-1.7.10-1.5.9.jar
AdvancedSolarPanel-1.7.10-3.5.1.jar
appliedenergistics2-rv2-stable-10.jar
BiblioCraft[v1.11.4][MC1.7.10].jar
Binnie Patcher 1.7.jar
binnie-mods-2.0-pre14-ru.jar
BiomesOPlenty-1.7.10-2.1.0.1826-universal.jar
buildcraft-7.1.16-ru.jar
buildcraft-compat-7.1.5.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CompactSolars-1.7.10-4.4.41.316-universal.jar
EnchantingPlus-1.7.10-3.0.2-d.jar
ExtraCells-1.7.10-2.3.9b188.jar
forestry_1.7.10-4.2.12.60.RU.jar
GalacticraftCore-1.7-3.0.12.454.jar
Galacticraft-Planets-1.7-3.0.12.454.jar
GraviSuite-1.7.10-2.0.3-ru.jar
Highlands-1.7.2-v-2.2.3.jar
ic2ca-1.7.10-1.14.5.06.jar
IC2NuclearControl-2.3.4a.jar
industrialcraft-2-2.2.821-exp-ru2.jar
ironchest-1.7.10-6.0.62.742-universal.jar
IronChestMinecarts-1.0.4.jar
lookingglass-1.7.10-0.2.0.00.jar
Metallurgy-1.7.10-4.0.8.97.jar
MetallurgyCore-1.7.10-4.0.4.18.jar
MicdoodleCore-1.7-3.0.12.454.jar
MineTweaker3-1.7.10-3.0.10B.jar
ModTweaker2-0.9.5.jar
mystcraft-1.7.10-0.12.3.01.jar
MystNEI-Plugin-1.7.10-02.01.09.jar
neiaddons-1.12.14.40-mc1.7.10.jar
NEIIntegration-MC1.7.10-1.1.2.jar
neiLotr-Alpha 0.4.1.jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
OptiFine_1.7.10_HD_U_D4.jar
QuarryPlus-1.7.10-2.1.0.jar
Railcraft_1.7.10-9.10.0.0.jar
Ruins-1.7.10.jar
SpACore-1.7.10-01.05.11.jar
twilightforest-1.7.10-2.3.7.jar
YourRecordsMod[1.7.10][v0.8.1]-ru.jar

java.lang.NoSuchMethodError: forestry.api.genetics.IMutation.getAllele0()Lforestry/api/genetics/IAllele;

[crash-2016-05-02_08.39.59-client.txt](https://github.com/Chocohead/Binnie-Patcher/files/244557/crash-2016-05-02_08.39.59-client.txt)

**Comment by Flexico** [comment]
I'm having this problem as well! Sure hope it can be fixed, as the database is an important tool.

**Comment by Chocohead** [comment]
@Flexico It'll be fixed next version.
