### ISSUE TITLE
Crash when right-clicking lab stand with something in hand, without Buildcraft installed

### ISSUE THREAD

**Issue by mezz** [Chocohead/Binnie-Patcher#2]
I had an apiarist database thing on top of a lab stand, and I right-clicked it while holding a vanilla chest.
Buildcraft is not in my pack.
https://gist.github.com/mezz/14af14a8f96235b1c429

Forestry used to include `buildcraft/api/tools/IToolWrench` but Forestry 4 no longer does.
I think you can get around this by including the class, or removing the wrench functions, or using `@Optional`.

**Comment by Chocohead** [comment]
Fixed in the next release.
