### ISSUE TITLE
Crash when opening Electrical Stimulator with Circuit Board

### ISSUE THREAD

**Issue by ghost** [Chocohead/Binnie-Patcher#20]
After updating from 1.6.3 to 1.8.1 my client crashes everytime I open the Electrical Stimulator. Rolling back to 1.6.3 seems to fix it.

https://paste.ee/p/cWYHT

**Comment by Chocohead** [comment]
That's not good at all. I'll see if I can find what's gone wrong.

**Comment by ghost** [comment]
I rolled back to 1.6.4 deleted the Stimulator and all Circuit boards then installed 1.8.1 again and cheated the items back in. Still crashes my game when trying to insert the circuit boards into the stimulator.

**Comment by Chocohead** [comment]
I think I have an idea what's going wrong...

**Comment by Chocohead** [comment]
The actual crash was completely different to the real cause, fixed next version.
