### ISSUE TITLE
OreDict wooden gears, please?

### ISSUE THREAD

**Issue by AnrDaemon** [Chocohead/Binnie-Patcher#22]
Right now, Scented Gear and Proven Gear are missing oredict registration (gearWood).

**Comment by Chocohead** [comment]
I guess I can add them, it just seems strange why you'd ever want to use them instead of a much cheaper gear made from normal sticks.

**Comment by AnrDaemon** [comment]
I just like my worlds orderly ;)
Thanks for your continued support! <3

**Comment by Chocohead** [comment]
Fixed next version.
