### ISSUE TITLE
Client crash when trying to craft.

### ISSUE THREAD

**Issue by noobyaran9** [Chocohead/Binnie-Patcher#23]
This is the crash report.

[crash-2016-06-28_20.36.07-client.txt](https://github.com/Chocohead/Binnie-Patcher/files/337031/crash-2016-06-28_20.36.07-client.txt)

**Comment by Chocohead** [comment]
What were you trying to craft?

**Comment by noobyaran9** [comment]
It just crashed on anything that require a crafting table to craft.

**Comment by Chocohead** [comment]
Cannot reproduce.
