### ISSUE TITLE
Crash when using the Analyst with a Tree

### ISSUE THREAD

**Issue by danielrossyamitrano** [Chocohead/Binnie-Patcher#26]
I haven't tried with butterflies yet, and with bees the Analyst seems to work properly, but every time I try to Analyse a tree (be it a vanilla tree or a forestry one) I get[ a crash like this one](http://pastebin.com/UHuHAaMP).
I'm using forestry 4.2.12.60 and binnie's mods 2.0-pre14.

**Comment by Chocohead** [comment]
Fairly certain I've already fixed that, try updating Binnie Patcher.

**Comment by danielrossyamitrano** [comment]
I think I already have the lastest version. unless there is a new addres

**Comment by danielrossyamitrano** [comment]
You were right. I had the 1.6 version of the patcher. I didn't know there was a new version (1.8)
