### ISSUE TITLE
Any plans to patch binnie's mods to forestry 5?

### ISSUE THREAD

**Issue by danielrossyamitrano** [Chocohead/Binnie-Patcher#27]
I just wanted to ask that. There is no bug _per se_ in this issue.

**Comment by Chocohead** [comment]
Since Binnie open sourced there's no point to trying to patch it past 1.7.10, if I was going to it would be from scratch using the assets.

**Comment by danielrossyamitrano** [comment]
So, will you?

**Comment by Chocohead** [comment]
I elaborated a little more here: https://github.com/Chocohead/Binnie-Patcher/issues/28#issuecomment-239892950
