### ISSUE TITLE
GUIs do not always update their displayed items

### ISSUE THREAD

**Issue by mezz** [Chocohead/Binnie-Patcher#3]
![2016-02-27_17 08 39](https://cloud.githubusercontent.com/assets/916092/13376624/abd50cf6-dd75-11e5-870b-69d79097ecd2.png)

This machine has just finished its job, and put a blank sequence into the slot at the right. The item in the middle should not be there any more. The machine knows there's no item in the middle (the red warning says so), but the GUI displays it anyway.

After clicking the item in the middle, it disappears.
![2016-02-27_17 08 43](https://cloud.githubusercontent.com/assets/916092/13376628/c533dc86-dd75-11e5-9f96-4b1f6125c02f.png)

This also often happens when pipes take items out of machines.

**Comment by Chocohead** [comment]
I've seen this myself too... and hoped no one else would. GUI syncing is complicated.

**Comment by mezz** [comment]
It has always been a problem, but I figure it's good to log the "real" bugs here. 
Binnie's tracker has hundreds of open bugs, most of which are resolved or invalid.
Even if you never fix it, at least people can be pointed here and see that it's a known bug.

**Comment by Chocohead** [comment]
Sounds like the best solution for the situation.

**Comment by Chocohead** [comment]
Finally fixed this
