### ISSUE TITLE
Crash with Forestry 4.2.2.50

### ISSUE THREAD

**Issue by henry232323** [Chocohead/Binnie-Patcher#30]
I am running Forestry 4.2.2.50, with Binnie's Mods pre14 and Binnie Patcher 1.7FIX
[crash-2016-09-17_10.08.19-client.txt](https://github.com/Chocohead/Binnie-Patcher/files/478254/crash-2016-09-17_10.08.19-client.txt)

**Comment by Chocohead** [comment]
You're using Binnie Mods 1.8.0 which is for MC 1.6.4, you should be using Pre 14.
