### ISSUE TITLE
Breaking an ExtraTrees door creates duplicates

### ISSUE THREAD

**Issue by bobs50000** [Chocohead/Binnie-Patcher#34]
I'm using:
Forestry - 1.7.10 - 4.2.16.64
Binnie's Mods - 2.0-pre14
Binnie Patcher - 1.8

If you place and break a door added by ExtraTrees from the top, it will drop 2 items instead of just 1
Breaking it from the bottom blocks drops 1 as expected
This bug does not occur if you use Binnie Patcher 1.6

**Comment by Chocohead** [comment]
Sounds #11 has caused both to drop.

**Comment by Chocohead** [comment]
Fixed next version.

**Comment by AnrDaemon** [comment]
Is that next version published anywhere yet?
