### ISSUE TITLE
Open source patcher code

### ISSUE THREAD

**Issue by KorDum** [Chocohead/Binnie-Patcher#35]
In Forestry repositories exists port to Forestry 4.2 (code name pre15).
https://github.com/ForestryMC/Binnie/tree/master-MC1.7.10
Maybe it makes sense to share the code with the developers so that they can continue the work?

**Comment by Chocohead** [comment]
There's not really as much code to share as bytecode instructions. Apart from some of the wood getting logic, which they already have something quite similar [here](https://github.com/ForestryMC/Binnie/blob/master-MC1.7.10/src/main/java/binnie/extratrees/FakeWorld.java#L20), the rest is instructions being added and removed. The most useful thing that could be gathered is probably the insertion locations of places that need fixing. I might clean it up a little and release it anyway though, I suppose people might be curious what kept their game alive for months ;)

**Comment by KorDum** [comment]
Thanks for answer!
It's important for me to know that I can build pre15 version from the Forestry repository and get exactly the same working (like the old mod + patcher). I can do it? Or pre15 not contains all fixes from patcher?

**Comment by Chocohead** [comment]
It should contain everything that Binnie Patcher did to ensure nothing crashed, which was a bulk of the changes, but there might be some smaller things that are missing like fixing the wood product page not working or doors dropping twice.

**Comment by KorDum** [comment]
Thank you very much for your work!
I hope you will give a list of fixed bugs (and tips for fixing them) in fork repository authors :)
