### ISSUE TITLE
Crash While Loading

### ISSUE THREAD

**Issue by SilverKytten** [Chocohead/Binnie-Patcher#37]
I've double and triple-checked that I'm using the most recent versions of each mod. I can't tell what's going wrong. 

[crash-2017-07-25_07.27.49-client.txt](https://github.com/Chocohead/Binnie-Patcher/files/1173131/crash-2017-07-25_07.27.49-client.txt)

**Comment by KorDum** [comment]
BinniePatcher is no longer needed if you use Binnie from pre15+ version.

**Comment by SilverKytten** [comment]
Ah, ok, thankyou.

**Comment by jikuja** [comment]
There should be one more update for this mod. @Chocohead can you consider adding versioned dependancy to binnie's mod to decrease amount of these problems?

**Comment by Galaxy-Voyager** [comment]
При запуске происходит вылет, клиент загружается нормально после того как Binnie Patcher был удален.
[errors.txt](https://github.com/Chocohead/Binnie-Patcher/files/1375540/errors.txt)
