### ISSUE TITLE
Electrical Stimulator Circuit Boards can be placed in any ISocketable slot

### ISSUE THREAD

**Issue by mezz** [Chocohead/Binnie-Patcher#4]
If you implement `ICircuitLayout.getSocketType()` and make sure the Electrical Stimulator also implements `ISocketable.getSocketType()` so they match, they will check for the the type correctly.

**Comment by Chocohead** [comment]
Implemented it in the circuit, need to do it in the stimulator.

**Comment by Chocohead** [comment]
Fixed in the next release.
