### ISSUE TITLE
Extra Bees registers Centrifuge recipes for disabled combs

### ISSUE THREAD

**Issue by mezz** [Chocohead/Binnie-Patcher#5]
There are lots of combs that have integration with other mods.
When the mod they work with is not there, they are hidden from NEI and have no products, but they still have centrifuge recipes.

![2016-02-27_17 32 51](https://cloud.githubusercontent.com/assets/916092/13376783/774f28c4-dd78-11e5-8b1c-fcaa404630a9.png)

**Comment by Chocohead** [comment]
Fixed in the next release.
