### ISSUE TITLE
[Notification] Modpack usage

### ISSUE THREAD

**Issue by spannerman79** [Chocohead/Binnie-Patcher#6]
Hello,

I know you have stated that you would rather to be notified of usage of Binnie-Patcher via [FTB](http://forum.feed-the-beast.com/threads/1-7-10-binnie-patcher.143722/) but I have found its better to have an actual issue raised then later closed due to the url structure of github vs forums.

Name of Pack: TBA

Modpack distrubtion: Technic via solder.io setup.

Modpack visibility: Private

Example of another permission obtained: https://github.com/GrowthcraftCE/Growthcraft-1.7/issues/57

**Comment by Chocohead** [comment]
If it's a private pack then you don't event need to strictly tell me, but thank you for doing so anyway, and yes you can use it.

**Comment by spannerman79** [comment]
I do realize that I don't need to strictly tell you but I would rather inform a modder so they know that their mod is being used and who knows - people might push me to push the modpack from being private into public.  Which would require me to inform modders anyway.

Also helps if enough of my friends convince me to use FTB Launcher - which you know how their permission system is based on regardless if the pack is public or private - permission **must** be obtained.  And for that easier to point to a Github issue then try and crawl through forum posts _ugh_
