### ISSUE TITLE
Weird DragonApi, Waila, and world place crash

### ISSUE THREAD

**Issue by vagaprime** [Chocohead/Binnie-Patcher#7]
I was playing a mod pack last night and tried to place extra tree dark oak fence an had the game crash.

here is a link to both the server and client crash logs.

http://pastebin.com/NT5v5rtR

http://pastebin.com/dA0dNxzN

Also the fences are showing up in your inventory as half slab's

Similar crash logs from another user of the mod pack

https://www.dropbox.com/sh/6d28pb6b99mqgmy/AAAFqBjzkR4oBv5zjuqdLtdTa?dl=0

**Comment by Chocohead** [comment]
Which version of Binnie Patcher are you using? I'm sure I fixed fences.

**Comment by vagaprime** [comment]
Version 1.2

**Comment by Chocohead** [comment]
That'd do it, try updating to 1.6.

**Comment by vagaprime** [comment]
Will do

**Comment by Chocohead** [comment]
Fences definitely work in the newest version.
