### ISSUE TITLE
No secondary drop

### ISSUE THREAD

**Issue by LostRuby** [Chocohead/Binnie-Patcher#8]
I apologize for my English , but I am using Google translator.
My problem is that bees produce only the main drop but not the secondary . I do not know if it depends on your mod , from that of Binnie , from Gendustry or from forestry itself , I just know that when I write all four mod are updated to the latest version , thanks in advance for the help you'll want to give me.
P.S .: Thank you for your work

**Comment by Chocohead** [comment]
The secondary drop only happens when the Bees are in their native biome (ie, one they'll work in with a temperature and humidity tolerance of 0). That's a Forestry 4 change/fix.
