### ISSUE TITLE
Extra Bees Mod is not recognized by Ex Nihilo

### ISSUE THREAD

**Issue by Obscuras** [Chocohead/Binnie-Patcher#9]
Hi! 

First - Thank you for your good work! 

I'm not sure if you can fix this or if this is on the Ex Nihilo side. 

I'm playing a Glass of Garden (Botania "Skyblock") private modpack with several mods like 
- Forestry (4.2.9.57)
- Binnie Core (2.0-pre14)
- Binnie Patcher (1.7.1)
- Ex Nihilo (1.38-49)
  (only mentioned some of the affected mods + version)

In the [Ex Nihilo source](https://bitbucket.org/Erasmus_Crowley/ex-nihilo/src/b0b582d711263ccb3f2048f9c8fdb9982a5340da/src/main/java/exnihilo/compatibility/foresty/HiveList.java?at=master&fileviewer=file-view-default) you can find this function:

```
public static boolean generateExtraBeesHives()
        {
        Block ebHives = GameRegistry.findBlock("ExtraBees", "hive");;
        if (ebHives != null)
        {
            extraBeesHives = new ItemStack(ebHives, 1, 0);

            generateWaterHive();
            generateRockHive();
            generateNetherHive();

            ExNihilo.log.info("Compatibility OK!: Extra Bees");

            return true;
        }
        else
        {
            ExNihilo.log.info("Compatibility FAIL!: Extra Bees");
        }

        return false;
    }

```

And in the logfile you can find these lines:

> [Client thread/INFO]: Beginning Hive Registry...
> [Client thread/INFO]: Compatibility OK!: Forestry Bees
> [Client thread/INFO]: Compatibility FAIL!: Extra Bees
> [Client thread/INFO]: Compatibility OK!: Magic Bees
> [Client thread/INFO]: Hive Registry Completed!

So Ex Nihilo is not able to recognize the Extra Bee Hives. I'm wondering if this has something to do with your changes to Extra Bees? Maybe there is something you can do to fix this?
Or maybe Ex Nihilo is not completely compatible to the latest Binnie Core?

Thank you for your time!

keep up the good work,

Obscuras

**Comment by Chocohead** [comment]
That's weird, I can copy the exact code and it works fine.

**Comment by Obscuras** [comment]
hm. strange thing. Well, my modlist is quite long, so maybe it has to do something with any of the other mods...
I'll try it again with a much shorter list, give me a moment...

**Comment by Chocohead** [comment]
Oh no, I see the issue. The source doesn't match the latest version on Curse, it checks for Magic Bees then adds Extra Bees compat and vice versa, which would explain why it's broken. Issue 8 is the exact problem and in the source itself it's been fixed, just there isn't a version with it in.

It can be fixed from Ex Nihilo actually releasing a version with that fix in (or you backdating to an older version which apparently doesn't have the bug if the issue is right).

**Comment by Obscuras** [comment]
yeah, I just compiled the source and it's obviously an older version (1.37) and not compatible. But again, thanks for looking into it. Maybe I can find a compatible version or another way...
